# Generated by Django 5.1.6 on 2025-02-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationroom',
            name='room_name',
            field=models.TextField(default='Room 0'),
        ),
    ]
